version: 2
updates:
  # Enable Dependabot for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MakerCorn"
    assignees:
      - "MakerCorn"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group patch updates to reduce PR noise
    groups:
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security updates get separate PRs
    security-updates:
      enabled: true
    
  # Enable Dependabot for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "MakerCorn"
    assignees:
      - "MakerCorn"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # Enable Dependabot for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "MakerCorn"
    assignees:
      - "MakerCorn"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"