version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MakerCorn"
    assignees:
      - "MakerCorn"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Remove deprecated security-updates field

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "MakerCorn"
    assignees:
      - "MakerCorn"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "MakerCorn"
    assignees:
      - "MakerCorn"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

# Use top-level groups for grouping PRs across update types
groups:
  pip-minor-patch-updates:
    patterns:
      - "*"
    update-types:
      - "minor"
      - "patch"
  github-actions-minor-patch-updates:
    patterns:
      - "*"
    update-types:
      - "minor"
      - "patch"
  docker-minor-patch-updates:
    patterns:
      - "*"
    update-types:
      - "minor"
      - "patch"
