apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft-toolkit-aws-service-account
  namespace: raft-toolkit
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: raft-toolkit
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/raft-toolkit-eks-role"
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-secret
  namespace: raft-toolkit
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: raft-toolkit
type: Opaque
data:
  # Base64 encoded AWS credentials (if not using IAM roles)
  aws-access-key-id: ""      # Optional: Base64 encoded AWS Access Key ID
  aws-secret-access-key: ""  # Optional: Base64 encoded AWS Secret Access Key
  role-arn: ""               # Optional: Base64 encoded IAM Role ARN