apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: raft-toolkit-eks
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/part-of: raft-toolkit
    cloud.provider: aws

resources:
- ../../base
- aws-load-balancer-controller.yaml
- aws-iam-service-account.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml
- pvc-patch.yaml

configMapGenerator:
- name: eks-specific-config
  literals:
  - CLOUD_PROVIDER=aws
  - AWS_REGION=us-west-2
  - STORAGE_TYPE=ebs-gp3

images:
- name: raft-toolkit
  newName: your-account-id.dkr.ecr.us-west-2.amazonaws.com/raft-toolkit
  newTag: latest

commonLabels:
  cloud.provider: aws
  deployment.environment: eks

namespace: raft-toolkit