apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft-toolkit-azure-identity
  namespace: raft-toolkit
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: raft-toolkit
  annotations:
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-identity-secret
  namespace: raft-toolkit
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: raft-toolkit
type: Opaque
data:
  # Base64 encoded Azure identity values
  client-id: ""     # Required: Base64 encoded Azure Client ID
  tenant-id: ""     # Required: Base64 encoded Azure Tenant ID
  subscription-id: ""  # Optional: Base64 encoded Azure Subscription ID