apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raft-toolkit-input-pvc
  namespace: raft-toolkit
spec:
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raft-toolkit-output-pvc
  namespace: raft-toolkit
spec:
  storageClassName: azurefile-csi-premium
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi