apiVersion: apps/v1
kind: Deployment
metadata:
  name: raft-toolkit-web
  namespace: raft-toolkit
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        # GCP-specific annotations
        iam.gke.io/gcp-service-account: "raft-toolkit@your-project-id.iam.gserviceaccount.com"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      # GCP-specific configuration
      serviceAccountName: raft-toolkit-gcp-service-account
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        cloud.google.com/gke-nodepool: "default-pool"
      tolerations:
      - key: "cloud.google.com/gke-preemptible"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: raft-toolkit-web
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
        # GCP-specific environment variables
        - name: GOOGLE_CLOUD_PROJECT
          value: "your-project-id"
        - name: GCP_REGION
          value: "us-central1"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/var/secrets/google/key.json"
        # Enable Vertex AI integration if available
        - name: VERTEX_AI_ENABLED
          value: "false"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcp-service-account-key
          optional: true