apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft-toolkit-gcp-service-account
  namespace: raft-toolkit
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: raft-toolkit
  annotations:
    iam.gke.io/gcp-service-account: "raft-toolkit@your-project-id.iam.gserviceaccount.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account-key
  namespace: raft-toolkit
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: raft-toolkit
type: Opaque
data:
  # Base64 encoded service account key JSON
  key.json: ""  # Optional: Base64 encoded GCP service account key JSON