apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: raft-toolkit-gks
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/part-of: raft-toolkit
    cloud.provider: gcp

resources:
- ../../base
- gcp-service-account.yaml
- gcp-storage-classes.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml
- pvc-patch.yaml

configMapGenerator:
- name: gks-specific-config
  literals:
  - CLOUD_PROVIDER=gcp
  - GCP_REGION=us-central1
  - STORAGE_TYPE=pd-ssd

images:
- name: raft-toolkit
  newName: gcr.io/your-project-id/raft-toolkit
  newTag: latest

labels:
- pairs:
    cloud.provider: gcp
    deployment.environment: gks

namespace: raft-toolkit