apiVersion: v1
kind: Service
metadata:
  name: raft-toolkit-web-service
  namespace: raft-toolkit
  annotations:
    # GCP Load Balancer annotations
    cloud.google.com/load-balancer-type: "External"
    cloud.google.com/backend-config: '{"default": "raft-toolkit-backend-config"}'
    cloud.google.com/health-check-path: "/health"
    cloud.google.com/health-check-interval: "10"
    cloud.google.com/health-check-timeout: "5"
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0  # Restrict this to your IP ranges in production
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: raft-toolkit-backend-config
  namespace: raft-toolkit
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 8000
  connectionDraining:
    drainingTimeoutSec: 30
  timeoutSec: 600