apiVersion: v1
kind: Secret
metadata:
  name: raft-toolkit-secrets
  namespace: raft-toolkit
  labels:
    app.kubernetes.io/name: raft-toolkit
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: raft-toolkit
type: Opaque
data:
  # Base64 encoded secrets - replace with your actual values
  # Use: echo -n "your_secret_value" | base64
  
  # OpenAI API Configuration
  OPENAI_API_KEY: ""  # Required: Base64 encoded OpenAI API key
  OPENAI_API_BASE_URL: aHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MQ==  # https://api.openai.com/v1
  
  # Azure OpenAI Configuration (optional)
  AZURE_OPENAI_KEY: ""  # Optional: Base64 encoded Azure OpenAI key
  AZURE_OPENAI_ENDPOINT: ""  # Optional: Base64 encoded Azure endpoint
  AZURE_OPENAI_API_VERSION: MjAyNC0wMi0wMQ==  # 2024-02-01
  
  # External Service Configuration (optional)
  SENTRY_DSN: ""  # Optional: Base64 encoded Sentry DSN for error tracking
  DATADOG_API_KEY: ""  # Optional: Base64 encoded DataDog API key